# Generated by Django 3.0.3 on 2020-03-01 17:05

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todomodel',
            name='created',
            field=models.DateField(auto_now_add=True, default=datetime.datetime(2020, 3, 1, 17, 5, 20, 161211, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
